{% set version = "0.11" %}

package:
  name: pyranha
  version: {{ version }}

source:
  fn: piranha-{{ version }}.tar.gz
  url: https://github.com/bluescarni/piranha/archive/v{{ version }}.tar.gz
  sha256: ab5782696a40888726c752c06a4b60783eda28ee4736b56083b96a53fd9a6230

build:
  number: 1000
  skip: true        # [win or py34]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
  host:
    - gmp
    - mpfr
    - boost
    - bzip2
    - zlib
    - msgpack-c
    - python
  run:
    - gmp
    - mpfr
    - boost
    - bzip2
    - zlib
    - python
    - mpmath
    - numpy

test:
  imports:
    - pyranha
  commands:
    - python -c "import pyranha.test; pyranha.test.run_test_suite()";

about:
  home: https://github.com/bluescarni/piranha
  license: GPL v3 and LGPL v3
  license_file: COPYING.lgpl3
  summary: 'Python bindings to Piranha computer algebra system.'

extra:
  recipe-maintainers:
    - isuruf
    - bluescarni
