{% set version = "0.11" %}

package:
  name: pyranha
  version: {{ version }}

source:
  fn: piranha-{{ version }}.tar.gz
  url: https://github.com/bluescarni/piranha/archive/v{{ version }}.tar.gz
  sha256: ab5782696a40888726c752c06a4b60783eda28ee4736b56083b96a53fd9a6230
  patches:
    - boost_python3.diff

build:
  number: 5
  skip: true        # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - gmp
    - mpfr
    - libboost-python-devel
    - libboost-devel
    - bzip2
    - zlib
    - msgpack-cxx
    - python
  run:
    - python
    - mpmath
    - numpy

test:
  imports:
    - pyranha
  commands:
    - python -c "import pyranha.test; pyranha.test.run_test_suite()";

about:
  home: https://github.com/bluescarni/piranha
  license: GPL-3.0-or-later OR LGPL-3.0-or-later
  license_file: COPYING.lgpl3
  summary: 'Python bindings to Piranha computer algebra system.'

extra:
  recipe-maintainers:
    - isuruf
    - bluescarni
