travis:
  secure:
    BINSTAR_TOKEN: Nhu54P1scjBRXsP8rMaoBllCuxSrf8H6bEfzmwWVSFfjLaEBfJDOfNTCMp8L3YpjNq6mEqGDJkd/FtRB+PLQ/+BcYUWKghOOKLarV+CfTV5av8g8tmej8MDYlt8o2zLTCF9m4RtHnM/nrfq17jk6ZK8meX0o3QEKIyRREvxFosnSAYVc+NMecqrDZft2qhsCcTYaWYESVWPP789gVBxCRt2+Wj7SeZ5T5p7qAoL0Z8HPn+bCanWUpZLSz3F4/4SmuSbFdp0nUCrtkOBRMIlMTG19avh4l9j+yMuCH4KXsIAcwygLJPlA5rK7rVju4NZJwMo/tjNfCUYRuwqE0icw4vqkcjYfYptOvKyjI0lFSW+1BDDtL5ZLcMuOOcPP8HHYLMtzrwh36QpN4yNu3XHIUceMSJcVvQHVR3GevAOb47rhk5G9TqDxrPKLBqMt5FHRdfoInv58BTvL2oH/I7Pea80SzKhg/ulMHnUWJ/uJtt23PA8jRrrShUg7QFOQSlf1LlLdnUO0wp5DB2Y7yLblkcowtP4h7IfM1DQ+lD0J4cz/enEUQorW4lIo+MmyK69/dIB62zPECioGRzmr+VyR5uR6Wsr/OB0vDv5goIkQEwd50rTrbEfA4MuZ1jE819lEdU6qdCJ3deYlUN/OUNFKyr955Frvjvt3/K1HNCKocSA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
