travis:
  secure:
    BINSTAR_TOKEN: obPcPnj3m2MQoNFmsR/+YZyINqkXn7mpPpvw5m55ewpaZ2rjXZXBLOdsggJrX0exeSZoXOGEsIxJ2Q29TH6544LjPEIEq14rF6Spt4U0tIsuoDZqGR436W8H2d3eAcGKnIYo9+YGSdb2yPzmi2FSL5kCA+H86+BpljrNoSE95O7RGJmoG3W7xqmxsv0ikY1ZYBWikL1NY5qy9SnoK6MWexupHRanwiGJUyv4dSidZZb4uWS07slEq2kYSo+a/YhXJBfyJirnvVdTSl0X3v+yU4r0cnZjjHEP92EzXgFYaFAOqtvZvmgJRNXYCmu5o0J8J4b5gkKmXS/799GhBDU+ybBno05B2SZi9Qpp70iX4P+S2C3Qq/XLw/jhYcgrW3/Tj49ewYyYSA/kln0GO0WwHyumhFbMtM0klLCuVyFPL/oBBVd6kOzcU52ALw6C6XO1LqXDN2SR/nr4lcta0eiNSu3Dxo+TXXNiZ92puwDrvXN1YtvpD9AnhzsjAaNSKxcbz6JlnxWFvvb03RfXT/JNeD/XBI0OQ1Mtxe+uuF4DCq92yWIiq9p3sdbDLBftVCWDDa6PelvJ7rOMePtbECu0JB21ZFUy9sVuRX43G4/LaQvaajS/GageMwP4eZDEcuOJkHpCvAZ7qmQKp0XWewLWrmGgpKg3jgXkU6XjtXK1zkQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
